- name: Install dependencies
  run: npm install

- name: Add Android platform (Capacitor)
  run: npx cap add android   # <-- fixed, no --skip-npm

- name: Setup Java 17
  uses: actions/setup-java@v4
  with:
    distribution: temurin
    java-version: 17

- name: Setup Android SDK
  uses: android-actions/setup-android@v3

- name: Copy web to native
  run: npx cap copy android
